package proyectouniversae;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author zabal
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private ImageIcon originalIcon;
    private ImageIcon originalIcon2;
    private ImageIcon originalIcon3;
    private ImageIcon originalIcon4;
    private ImageIcon originalIcon5;
    private ImageIcon originalIcon6;

    public PantallaPrincipal() {
        initComponents();
        originalIcon = (ImageIcon) labelMiniatura0.getIcon();
        originalIcon2 = (ImageIcon) labelMiniatura1.getIcon();
        originalIcon3 = (ImageIcon) labelMiniatura2.getIcon();
        originalIcon4 = (ImageIcon) labelMiniatura3.getIcon();
        originalIcon5 = (ImageIcon) labelMiniatura4.getIcon();
        originalIcon6 = (ImageIcon) labelMiniatura5.getIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelMiniatura0 = new javax.swing.JLabel();
        labelMiniatura2 = new javax.swing.JLabel();
        labelMiniatura1 = new javax.swing.JLabel();
        labelMiniatura3 = new javax.swing.JLabel();
        labelMiniatura4 = new javax.swing.JLabel();
        labelMiniatura5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        icon0 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon5 = new javax.swing.JLabel();
        icon6 = new javax.swing.JLabel();
        icon7 = new javax.swing.JLabel();
        icon8 = new javax.swing.JLabel();
        icon9 = new javax.swing.JLabel();
        icon10 = new javax.swing.JLabel();
        icon11 = new javax.swing.JLabel();
        icon12 = new javax.swing.JLabel();
        icon13 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        labelFondoBase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        labelMiniatura0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton0.png"))); // NOI18N
        labelMiniatura0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura0MouseExited(evt);
            }
        });

        labelMiniatura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton2.png"))); // NOI18N
        labelMiniatura2.setAutoscrolls(true);
        labelMiniatura2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura2MouseExited(evt);
            }
        });

        labelMiniatura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton1.png"))); // NOI18N
        labelMiniatura1.setAutoscrolls(true);
        labelMiniatura1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura1MouseExited(evt);
            }
        });

        labelMiniatura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton3.png"))); // NOI18N
        labelMiniatura3.setAutoscrolls(true);
        labelMiniatura3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura3MouseExited(evt);
            }
        });

        labelMiniatura4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton4.png"))); // NOI18N
        labelMiniatura4.setAutoscrolls(true);
        labelMiniatura4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura4MouseExited(evt);
            }
        });

        labelMiniatura5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMiniatura5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazHome/Miniaturas simuladores/HomeButton5.png"))); // NOI18N
        labelMiniatura5.setAutoscrolls(true);
        labelMiniatura5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelMiniatura5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMiniatura5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMiniatura5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelMiniatura3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura0, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMiniatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(labelMiniatura4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMiniatura2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMiniatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura0, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMiniatura4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMiniatura5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 1550, 880));

        jPanel2.setOpaque(false);

        icon0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton8.png"))); // NOI18N
        jPanel2.add(icon0);

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton0.png"))); // NOI18N
        jPanel2.add(icon1);

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton1.png"))); // NOI18N
        jPanel2.add(icon2);

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton2.png"))); // NOI18N
        jPanel2.add(icon3);

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton3.png"))); // NOI18N
        jPanel2.add(icon4);

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton4.png"))); // NOI18N
        jPanel2.add(icon5);

        icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton5.png"))); // NOI18N
        jPanel2.add(icon6);

        icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton6.png"))); // NOI18N
        jPanel2.add(icon7);

        icon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton7.png"))); // NOI18N
        jPanel2.add(icon8);

        icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton13.png"))); // NOI18N
        jPanel2.add(icon9);

        icon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton9.png"))); // NOI18N
        jPanel2.add(icon10);

        icon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton10.png"))); // NOI18N
        jPanel2.add(icon11);

        icon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton11.png"))); // NOI18N
        jPanel2.add(icon12);

        icon13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/Escudos/LauncherButton12.png"))); // NOI18N
        jPanel2.add(icon13);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 1550, 130));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        btnGame.setText("Game");
        btnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        labelFondoBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectouniversae/InterfazBase/FondoBase.png"))); // NOI18N
        labelFondoBase.setFocusTraversalPolicyProvider(true);
        labelFondoBase.setName(""); // NOI18N
        jPanel1.add(labelFondoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameActionPerformed
        new PantallaGame().setVisible(true);
    }//GEN-LAST:event_btnGameActionPerformed

    private void labelMiniatura0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura0MouseEntered
        // Obtener la imagen actual del JLabel
        ImageIcon currentIcon = (ImageIcon) labelMiniatura0.getIcon();
        Image currentImage = currentIcon.getImage();

        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage = currentImage.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Establecer la imagen escalada en el JLabel
        labelMiniatura0.setIcon(scaledIcon);

    }//GEN-LAST:event_labelMiniatura0MouseEntered

    private void labelMiniatura0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura0MouseExited
        labelMiniatura0.setIcon(originalIcon); // Reemplaza 'iconOriginal' con tu ícono original

    }//GEN-LAST:event_labelMiniatura0MouseExited

    private void labelMiniatura2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura2MouseEntered
        // Obtener la imagen actual del JLabel
        ImageIcon currentIcon = (ImageIcon) labelMiniatura2.getIcon();
        Image currentImage = currentIcon.getImage();

        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage = currentImage.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Establecer la imagen escalada en el JLabel
        labelMiniatura2.setIcon(scaledIcon);
    }//GEN-LAST:event_labelMiniatura2MouseEntered

    private void labelMiniatura2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura2MouseExited
        labelMiniatura2.setIcon(originalIcon); // Reemplaza 'iconOriginal' con tu ícono original
    }//GEN-LAST:event_labelMiniatura2MouseExited

    private void labelMiniatura1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura1MouseEntered
        ImageIcon currentIcon2 = (ImageIcon) labelMiniatura1.getIcon();
        Image currentImage8 = currentIcon2.getImage();
        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage2 = currentImage8.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(scaledImage2);
        // Establecer la imagen escalada en el JLabel
        labelMiniatura1.setIcon(scaledIcon2);
    }//GEN-LAST:event_labelMiniatura1MouseEntered

    private void labelMiniatura1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura1MouseExited
        labelMiniatura1.setIcon(originalIcon2); // Reemplaza 'iconOriginal' con tu ícono original
    }//GEN-LAST:event_labelMiniatura1MouseExited

    private void labelMiniatura3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura3MouseEntered
        // Obtener la imagen actual del JLabel
        ImageIcon currentIcon4 = (ImageIcon) labelMiniatura3.getIcon();
        Image currentImage4 = currentIcon4.getImage();

        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage4 = currentImage4.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon4 = new ImageIcon(scaledImage4);

        // Establecer la imagen escalada en el JLabel
        labelMiniatura3.setIcon(scaledIcon4);
    }//GEN-LAST:event_labelMiniatura3MouseEntered

    private void labelMiniatura3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura3MouseExited
        labelMiniatura3.setIcon(originalIcon4); // Reemplaza 'iconOriginal' con tu ícono original
    }//GEN-LAST:event_labelMiniatura3MouseExited

    private void labelMiniatura4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura4MouseEntered
        // Obtener la imagen actual del JLabel
        ImageIcon currentIcon5 = (ImageIcon) labelMiniatura4.getIcon();
        Image currentImage = currentIcon5.getImage();

        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage5 = currentImage.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon5 = new ImageIcon(scaledImage5);

        // Establecer la imagen escalada en el JLabel
        labelMiniatura4.setIcon(scaledIcon5);
    }//GEN-LAST:event_labelMiniatura4MouseEntered

    private void labelMiniatura4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura4MouseExited
        labelMiniatura4.setIcon(originalIcon5); // Reemplaza 'iconOriginal' con tu ícono original
    }//GEN-LAST:event_labelMiniatura4MouseExited

    private void labelMiniatura5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura5MouseEntered
        // Obtener la imagen actual del JLabel
        ImageIcon currentIcon6 = (ImageIcon) labelMiniatura5.getIcon();
        Image currentImage6 = currentIcon6.getImage();

        // Escalar la imagen cuando el ratón entra en el JLabel
        Image scaledImage6 = currentImage6.getScaledInstance(450, 350, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon6 = new ImageIcon(scaledImage6);

        // Establecer la imagen escalada en el JLabel
        labelMiniatura5.setIcon(scaledIcon6);
    }//GEN-LAST:event_labelMiniatura5MouseEntered

    private void labelMiniatura5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMiniatura5MouseExited
        labelMiniatura5.setIcon(originalIcon6); // Reemplaza 'iconOriginal' con tu ícono original
    }//GEN-LAST:event_labelMiniatura5MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel icon0;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon10;
    private javax.swing.JLabel icon11;
    private javax.swing.JLabel icon12;
    private javax.swing.JLabel icon13;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel icon7;
    private javax.swing.JLabel icon8;
    private javax.swing.JLabel icon9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelFondoBase;
    private javax.swing.JLabel labelMiniatura0;
    private javax.swing.JLabel labelMiniatura1;
    private javax.swing.JLabel labelMiniatura2;
    private javax.swing.JLabel labelMiniatura3;
    private javax.swing.JLabel labelMiniatura4;
    private javax.swing.JLabel labelMiniatura5;
    // End of variables declaration//GEN-END:variables
}
